# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 545d6602d22db56ca0b4fc8bc5a2899a1158c18bbfcb6ed77869e9f15d670c86a39b530c94139901a1e619aca2e2a29aef91d214c8bb762b7d7c021add0911f3

test:
  secret_key_base: 917d06d09bfb8b349105aff99f6ab41a2bef05cf51fe9d3320c7e8df19c5181381f25c8eb6d476b387be2a9f994377a4c8bcb3209826cc6b86d9d25b26336cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
